on:
  push:
    branches:
      - '!main'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
        - name: create pull request
          run: gh pr create -B dev -H ${{ github.ref_name }} --title 'Merge ${{ github.ref_name }} into dev' --body 'Created by Github action' --repo ParkerShelton/Portfolio-Website